### ISSUE TITLE
Cannot resolve fibers in optimism

### ISSUE THREAD

**Issue by viztor** [benjamn/optimism#6]
WARNING in ./node_modules/optimism/lib/local.js

Module not found: Error: Can't resolve 'fibers' in '/Users/***/node_modules/optimism/lib'
 @ ./node_modules/optimism/lib/local.js
 @ ./node_modules/optimism/lib/index.js
 @ ./node_modules/apollo-cache-inmemory/lib/optimism.js
 @ ./node_modules/apollo-cache-inmemory/lib/readFromStore.js
 @ ./node_modules/apollo-cache-inmemory/lib/index.js

**Comment by benjamn** [comment]
What version of `optimism` are you using?

**Comment by brazosd** [comment]
Got this also with optimism@0.6.5

**Comment by benjamn** [comment]
What bundler are you using? Webpack? Rollup? Something else? The import of `fibers` should fail and be caught, so any error reported by your bundler is a false positive:
https://github.com/benjamn/optimism/blob/84624ab46ffeba7e724fe70b53c4fed16f251801/lib/local.js#L11-L18
Please feel free to provide any more information that seems relevant.

**Comment by viztor** [comment]
I'm using Webpack. It is just a warning
I was just bit confused and concerned if there were something wrong on my end.
From your reply, It appears it's just a global-checking mechanism.

I'm not sure how other lib handle things like this, or maybe there's something wrong with my webpack config?

**Comment by brazosd** [comment]
Webpack also.  Thanks.

**Comment by kevinmarrec** [comment]
Got the warning too, using `apollo-cache-inmemory` which depends on `optimism`

**Comment by swernerx** [comment]
I see the same warning - also using apollo inmemory cache. Looks like `index.js` is importing `local.js` which is importing `fibers`, but `fibers` is only declared as a `devDepenency`.

**Comment by Torsten85** [comment]
This happens with webpack > 4.16.2: https://github.com/webpack/webpack/releases/tag/v4.16.2
Related change: "handle module.require like require"

Here is an related issue: https://github.com/webpack/webpack/issues/7777

**Comment by viztor** [comment]
Any plan on fixing it?

**Comment by benjamn** [comment]
Does everyone understand the point of the code in question?

The goal is to import `fibers` if and only if the package is installed in `node_modules`, and otherwise silently swallow the exception. Webpack is attempting to be "helpful" with https://github.com/webpack/webpack/pull/7750, but fails to accommodate this legitimate use case (which works fine in Node and other runtime module systems)—another noisy warning perched precariously atop a mountain of unspecified hacks. Just so everyone is on the same page.

We've already "fixed" this sort of problem [once before](https://github.com/benjamn/optimism/commit/d45ebadb6556a0c80991f0c14a3efc976b0cf934), but I suppose we will have to keep working around Webpack's unsound and incomplete attempts to statically analyze this code.

**Comment by benjamn** [comment]
This approach (just published in `optimism@0.6.6`) ought to buy us some time:
https://github.com/benjamn/optimism/blob/5cc2edd952d435b33345bcef06f80ef9f3b05f7f/lib/local.js#L12

Your move, Webpack. But also… could you just… not? 😂
